#!/bin/bash

init_db() {
    local db_name="$1"
    local table_name="$2"
    sqlite3 $db_name "CREATE TABLE IF NOT EXISTS $table_name (
                        id INTEGER PRIMARY KEY,
                        hosts TEXT NOT NULL
                    )"
}

insert_db() {
    local db_name="$1"
    local table_name="$2"

    init_db $db_name $table_name

    while read host; do
        sqlite3 $db_name "INSERT INTO $table_name (hosts) VALUES ('$host')";
    done
}

main() {
    if [[ $# != 2 ]]; then
        echo -e "\nUsage: $0 <db_name> <table_name>"
        echo "Example:"
        echo -e "   cat subs.txt | $0 data.db subdomains\n"
        exit 0
    fi
    insert_db $1 $2
}

main $1 $2
